### ISSUE TITLE
Link to running map from readme

### ISSUE THREAD

**Issue by harry-wood** [gregrs-uk/python-fhrs-osm#1]
This looks interesting, but is there a running example of the resulting map anywhere? You should link it from the README

**Comment by gregrs-uk** [comment]
Thanks Harry, that's a good idea. I'm not quite there yet but I'll come back to this...

**Comment by gregrs-uk** [comment]
I've put an example HTML page for the Rugby District on Dropbox and linked to it from the readme (https://dl.dropboxusercontent.com/u/42978572/python-fhrs-osm-example/example.html)

**Comment by gregrs-uk** [comment]
I've now got this running for the entire of Great Britain: http://gregrs.dev.openstreetmap.org/fhrs/. Need to update the readme though, so re-opening this issue.
