### ISSUE TITLE
Support multiple fhrs:id values

### ISSUE THREAD

**Issue by rjw62** [gregrs-uk/python-fhrs-osm#11]
Sometimes a single object might have multiple FHRS entries associated with it. For example a residential address with two catering businesses being run from it, or a village hall that has an entry under its own name, and one for a weekly luncheon club.

In such cases, the best tagging approach is probably to use the standard semi-colon seperator to include more than one id value, e.g. fhrs:id=12345;67890. It would be good if the tool could support this use-case, and regard an OSM object so tagged a matching both the FHRS IDs.

For example, http://www.openstreetmap.org/way/137532109 has fhrs:id=831921;832952 but the tool doesn't appear to be matching it to either http://ratings.food.gov.uk/business/en-GB/832952/ or http://ratings.food.gov.uk/business/en-GB/831921/ . Oddly, nor it is reporting a "mismatch" at the bottom of http://gregrs.dev.openstreetmap.org/fhrs/district-122.html -- but perhaps I've misunderstood what should be displayed there. (I'd expect any OSM objects with unparsed or unmatched fhrs:id values to be listed there.)

**Comment by gregrs-uk** [comment]
Thanks Robert. I won't have any time very soon to look at this, but it would certainly be good if OSM entities with multiple fhrs:ids were supported.

Currently, the OSM fhrs:id tag is stored as an INT in the database (see https://github.com/gregrs-uk/python-fhrs-osm/blob/master/fhrs_osm/__init__.py#L541), so any records with semicolons will currently be discarded here: https://github.com/gregrs-uk/python-fhrs-osm/blob/master/fhrs_osm/__init__.py#L684

**Comment by SK53** [comment]
+1 for this. Other examples: Department Store selling food goods (eg. as gifts) with a cafe. (Obviously it may be that the cafe is mapped separately, but not always); schools with after-school & breakfast clubs which have separate fhrs:ids. I've also seen a sandwich shop which trades as a pizzeria in the evening from exactly same premises with a different id.

It's also possible that historical ids might be included in the fhrs:id, these should be in old_fhrs:id or similar. An example:  [http://www.openstreetmap.org/node/2109855832](http://www.openstreetmap.org /node/2109855832) (apologies, slightly contrived as I added the data today)

**Comment by gregrs-uk** [comment]
Just adding this list of errors inserting OSM data into the database as of 9/10/16: [db-insert-errors.txt](https://github.com/gregrs-uk/python-fhrs-osm/files/518181/db-insert-errors.txt)

You can see the OSM entities with multiple fhrs:ids triggering `DataError('invalid input syntax for integer:`... Some of them are separated by just a semicolon and some a semicolon plus a space.

There are currently 24 OSM entities with multiple fhrs:ids and 5 others with something invalid in the fhrs:id tag. It would be good to include these invalid ones in the database so that they pop up in the list of unmatched tags.

**Comment by gregrs-uk** [comment]
I've changed the database structure so that OSM entities with multiple fhrs:ids separated by semicolons will now be imported. These will show up in the list of mismatches at the bottom of each district page for now. The update script should recreate the district pages overnight.

**Comment by gregrs-uk** [comment]
[EdLoach comments](https://github.com/gregrs-uk/fhrs-osm-stats/issues/2):

It is possible I'm tagging this situation wrong, but as an example:
[OSM way representing business](http://www.openstreetmap.org/way/191821917)
This seems to have been inspected as both [848651](http://ratings.food.gov.uk/business/en-GB/848651/) and [999268](http://ratings.food.gov.uk/business/en-GB/999268/) on the same day, with the only difference I can see is that one used 'and' and one uses '&', so I added both values separated by a ;

This is likely to show as a mis-match [as per other examples in the area](http://gregrs.dev.openstreetmap.org/fhrs/district-44.html)

**Comment by rjw62** [comment]
PR #73 contains a possible solution to split ";"-separated multi-valued fhrs:id tags when they're imported, and handle each as a separate number.

**Comment by gregrs-uk** [comment]
Closed by #73. Many thanks.
