### ISSUE TITLE
Improve parsing of FHRS addresses into OSM tags

### ISSUE THREAD

**Issue by iccaldwell** [gregrs-uk/python-fhrs-osm#12]
Instead of generating the tag  fixme:addr1 split addr1 at the first space and set the tags  addr:housenumber and addr:street this will be correct over 90% of the time.

**Comment by SK53** [comment]
In the past I've merged the 4 address fields & matched street name to OSM; anything to left of that can be parsed for housenumber, name. This does need geometry operations. Some councils put absolutely everything in addr1.

**Comment by gregrs-uk** [comment]
Address parsing is implemented in [fhodot](https://github.com/gregrs-uk/fhodot), which will soon replace the original FHRS/OSM comparison tool
