### ISSUE TITLE
Multiple fixme:addr3 tags

### ISSUE THREAD

**Issue by craigw84** [gregrs-uk/python-fhrs-osm#19]
Some places in the FHRS data have 4 lines for the address. If you click the "Add tags in JOSM" option, it has 2 fixme:addr3 tags. So only one of them actually gets added to the object.

It would be more useful if one of these tags was fixme:addr4 (and fixme:addr5 if there's any longer addresses).

**Comment by gregrs-uk** [comment]
Thanks for spotting this. There is a simple [typo on this line](https://github.com/gregrs-uk/python-fhrs-osm/blob/master/fhrs_osm/__init__.py#L346), which I'll fix it when I get a chance (unless someone else can get to it sooner).

The FHRS database only has 4 address lines by the way, so fixme:addr4 will the the highest number required.

**Comment by gregrs-uk** [comment]
Fixed and pushed to dev server
