### ISSUE TITLE
More clickable links in overview map

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#20]
[Requested by Steve Doerr](https://lists.openstreetmap.org/pipermail/talk-gb/2016-October/019403.html):

I've now reached the stage where I need to look more at the upper map, where there seem to be fewer clickable links. If you could provide links to OSM for every dot on the map, that would be helpful. (If you're showing them on your map, you must have derived a long/lat which you could link to.)

**Comment by danstowell** [comment]
Yes this would be handy. I looked at the existing code and sketched a URL constructor along the lines of

```
   SELECT CONCAT('OSM: <a href=\"" + self.osm_url_prefix + "',\n" +
           "                   TRIM(TRAILING ' ' FROM osm_type),\n" +
           "                   '/', osm_id, '\">', osm_name, '</a>'\n" +
           "                   '<br /><a href=\"" + self.josm_url_prefix + "',"
           "                   'load_object?objects=', substring(osm_type from 1 for 1),\n" +
           "                   osm_id,
           "                   '\">Load object in JOSM</a>') AS text,\n" +
```

before I realised the conditional-string-construction-inside-conditional-string-construction (in get_overview_geojson()) was going to be too tricky for me to modify by myself...
