### ISSUE TITLE
Don't use fhrs:id already in OSM for suggested matches

### ISSUE THREAD

**Issue by spindr** [gregrs-uk/python-fhrs-osm#31]
If an fhrs:id is already present in OSM data don't use it to suggest matches to other OSM objects.

Pre-filter the id's from FHRS to only suggest matches for id's not present in OSM data.

**Comment by gregrs-uk** [comment]
Thanks for this @spindr. Could you give an example?

**Comment by spindr** [comment]
Ok, a bit difficult to explain -- but here goes:

On Bristol district: http://gregrs.dev.openstreetmap.org/fhrs/district-284.html

Look at the leftmost suggested yellow match -- this should be "Our lady of the Rosary".

If you try to add tags in JOSM then it tries to add fhrs:id=311265 to https://www.openstreetmap.org/way/279905273#map=19/51.49817/-2.66263

But https://www.openstreetmap.org/way/404867388#map=18/51.49868/-2.66162 already has fhrs:id=311265

Hope that's clear(ish).

**Comment by gregrs-uk** [comment]
That makes perfect sense - thanks for spotting this.

**Comment by gregrs-uk** [comment]
Should be fixed. Will check it's working correctly after the update tomorrow morning

**Comment by gregrs-uk** [comment]
Update failed. Problem fixed and I'm just running it manually.

**Comment by gregrs-uk** [comment]
Looks fixed

**Comment by spindr** [comment]
Brilliant. Thanks for adding the enhancement.
