### ISSUE TITLE
Check synonyms and ignore low value words when suggesting matches

### ISSUE THREAD

**Issue by AndrewHain** [gregrs-uk/python-fhrs-osm#36]
Some larger chains often appear in FHRS under a company name (McDonalds Restaurants Ltd) or an older brand name (Kentucky Fried Chicken). You could add a table of synonyms to allow for this and offer more suggested matches. Also names differing in the word “the” aren’t always matched, for instance [The Falcons School for Girls](https://www.openstreetmap.org/way/391372244) misses [Falcon's School For Girls](http://ratings.food.gov.uk/business/en-GB/842463/).

**Comment by gregrs-uk** [comment]
The suggest matches view does currently match OSM names that are within the FHRS name or where the Levenshtein distance between the two is low. See around [here in the code](https://github.com/gregrs-uk/python-fhrs-osm/blob/master/fhrs_osm/__init__.py#L254).

This one has an extra word in the OSM name compared with the FHRS one, which is more unusual, and also has an apostrophe different.

**Comment by gregrs-uk** [comment]
[fhodot](https://github.com/gregrs-uk/fhodot), which will soon replace the original FHRS/OSM comparison tool, includes more sophisticated name matching
