### ISSUE TITLE
Some map markers are being obscured by other nearby markers

### ISSUE THREAD

**Issue by AndrewHain** [gregrs-uk/python-fhrs-osm#37]
The tool is only returning 1247 of 1530 establishments in Richmond upon Thames. The difference is greater than the number of redacted locations, for instance http://ratings.food.gov.uk/business/en-GB/353162 is not reported at the position on the map shown on the FHRS page.

**Comment by gregrs-uk** [comment]
Thanks for your bug report, Andrew. The tool is downloading all 1530 establishments from the FHRS API:

```
select count("FHRSID") from fhrs_establishments where "LocalAuthorityCode" = 527;
 count 
-------
  1530
(1 row)
```
I suspect the reason for the difference in number of establishments is related to the boundaries used. The process of splitting FHRS and OSM data into districts is as follows:

1. Import OS Boundary Line district boundaries (`import_bline_districts.sh`)
2. Import FHRS data for all districts (`get_fhrs_data.py`)
3. Import relevant OSM data for Great Britain (`get_osm_data.py`)
4. Compute which OS Boundary Line district FHRS and OSM points are within and add ID to the relevant database table (`process_data.py`)
5. Generate output files for each district using district_id column to filter (`create_output_files.py`)

Therefore if the boundary used by the FHRS data is different, we could see very different numbers of establishments. Some of the establishments originally belonging to Richmond upon Thames may now belong to other neighbouring districts.

Does that explain what you're seeing or is there something else going on?

**Comment by AndrewHain** [comment]
The missing establishments are a significant distance from the borough boundary; for instance [352990](http://ratings.food.gov.uk/business/en-GB/352990) and [353162](http://ratings.food.gov.uk/business/en-GB/353162) are missing but [878238](http://ratings.food.gov.uk/business/en-GB/878238) with the same postcode and a marker on the FHRS map page that is not obviously different is returned, just today also [928471](http://ratings.food.gov.uk/business/en-GB/928471). Similarly the next block returns [354194](http://ratings.food.gov.uk/business/en-GB/354194) but not [354509](http://ratings.food.gov.uk/business/en-GB/354509).

**Comment by gregrs-uk** [comment]
It would appear that 352990 (Pizza Go Go) and 353162 (Lalbagh) are being obscured by Babycakes and The Little Brownie Kitchen because they have very similar but not identical locations. The tool amalgamates FHRS establishments with identical locations into a single marker on the Leaflet map, but not ones that are just very close. This may be possible or may have too big an impact on time taken to produce the output files.

This may be a problem with the conversion to PostGIS geography type or perhaps the FHRS lat/lons are non-identical at source. I need to do some more investigation.

Extract from GeoJSON for overview map:
```
{
	"type": "Feature",
	"geometry": {
		"type": "Point",
		"coordinates": [-0.273965, 51.464446]
	},
	"properties": {
		"list": "Pizza Go Go (<a href=\"http://ratings.food.gov.uk/business/en-GB/352990/\"target=\"_blank\">FHRS</a>)<br />Lalbagh (<a href=\"http://ratings.food.gov.uk/business/en-GB/353162/\"target=\"_blank\">FHRS</a>)",
		"matched": 0,
		"matched_postcode_error": 0,
		"mismatch": 0,
		"fhrs": 2,
		"osm_with_postcode": 0,
		"osm_no_postcode": 0
	}
}, {
	"type": "Feature",
	"geometry": {
		"type": "Point",
		"coordinates": [-0.273964, 51.464446]
	},
	"properties": {
		"list": "Babycakes (<a href=\"http://ratings.food.gov.uk/business/en-GB/928471/\"target=\"_blank\">FHRS</a>)<br />The Little Brownie Kitchen (<a href=\"http://ratings.food.gov.uk/business/en-GB/878238/\"target=\"_blank\">FHRS</a>)",
		"matched": 0,
		"matched_postcode_error": 0,
		"mismatch": 0,
		"fhrs": 2,
		"osm_with_postcode": 0,
		"osm_no_postcode": 0
	}
}
```

**Comment by gregrs-uk** [comment]
Could use [one of these Leaflet plugins](http://leafletjs.com/plugins.html#clusteringdecluttering)

**Comment by gregrs-uk** [comment]
I investigated [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster), but it doesn't quite do what I'd like. I think it might be better to cluster the points using PostGIS by modifying the query that currently creates clusters based on locations being identical.

**Comment by gregrs-uk** [comment]
Example query for just the FHRS establishments table showing the troublesome establishments being clustered together:

```
select * from (
	select ST_AsText(ST_Centroid(ST_Collect(geog::geometry))) as centroid,
	array_agg("FHRSID") as fhrs_ids
	from (
		select "FHRSID",
		ST_ClusterDBSCAN(geog::geometry, 3.5/111111, 1) over () as cl_id,
		geog
		from fhrs_establishments
		where district_id = 218
	) as the_establishments
	group by cl_id
) as the_clusters
where fhrs_ids @> '{878238}'::int[];
```
```
          centroid           |           fhrs_ids            
-----------------------------+-------------------------------
 POINT(-0.2739645 51.464446) | {353162,352990,928471,878238}
(1 row)
```

**Comment by gregrs-uk** [comment]
Should be fixed - works on my machine. Will check server-generated page tomorrow.

**Comment by gregrs-uk** [comment]
Need to update readme to reflect PostGIS 2.3 requirement and testing versions.

**Comment by gregrs-uk** [comment]
Working correctly. See http://gregrs.dev.openstreetmap.org/fhrs/district-218.html
