### ISSUE TITLE
Improve map view when zoomed out

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#40]
Markers can be very densely packed, obscuring the map underneath. Use clustering to improve this whilst still seeing individual markers at lower zoom levels.

**Comment by harry-wood** [comment]
Personally I've never liked clustering that much as a technique. It's a fun gimmick for users to play with (especially those zany animated clusters people use with leaflet a lot) but it doesn't actually help understand the density of information very well. I think it's actually better to show just a load of markers (which is what is what you're doing!)

but I would raise a couple of similar but different ideas:
* You've chosen quite small circular markers, presumably to tackle this problem, but then you sometimes get the opposite problem. When the markers are very sparsely spread out (when you're zoomed in) it can be hard to notice them compared with other map details. So...  could they be made to get a little bigger as you zoom right in. Might be interesting to experiment.
* What if we wanted a more zoomed out map showing all the data across multiple council regions, or even the whole UK? For one thing the markers then would be too big, but also it starts to be too much data to load as markers at all. My favourite solution I've seen to this is sadly not used often. A sneaky trick transitioning from javascript markers at high zooms, into a transparent tile rendering of marker data, designed to look the same, but in raster. It's a trick google fusion tables provides into google maps. Also done by mapbox studio and cartodb when they show lots of data, but I wish there were more open-sourcey solutions like this, and I wish Keepright and osmose would use a trick like this for showing their many many markers.

~~I was mentioning this technique here too:
https://www.loxodrome.io/post/dense-spatial-data/#comment-3113107308 and mentioning [tippecanoe](https://github.com/mapbox/tippecanoe/blob/master/MADE_WITH.md) as a tool for the very zoomed out / very dense data.~~  Hmm. No apparently that disquss comment has gone

**Comment by gregrs-uk** [comment]
Thanks for the detailed comment, which will be very helpful.

I won't have time to improve this in the near future but may be able to have a look over the summer. Contributions from others are of course welcome.
