### ISSUE TITLE
add building=school & potentially others

### ISSUE THREAD

**Issue by stev-0** [gregrs-uk/python-fhrs-osm#42]
The official [tagging schema](http://wiki.openstreetmap.org/wiki/Tag:building=school?uselang=en) for schools is to tag amenity=school for the grounds and building=school for school buildings. As I assume the  address should be associated with the building, I think you should allow building=school tags as well which may then show more matches. I guess there could be duplicates with amenity=school as well however.

**Comment by gregrs-uk** [comment]
Thanks for adding this issue @stev-0. I've given it some consideration but think it would be best to leave it as is.

Firstly, it seems more common to add the `addr:xxx` tags to the `amenity=school` way, although adding it to the building or the entrance does seem to make some sense. (GB Taginfo reports 13,407 out of 30,196 `amenity=school`s having an `addr:postcode` tag but only 1,628 out of 24,906 `building=school`s having one.)

Secondly, the comparison tool will already fetch any node or way with an `fhrs:id` set, including `building=school`s, and use these in showing matches.

Thirdly, in order for the statistics to be vaguely accurate, it's beneficial for there to be only one OSM entity that would likely match an FHRS establishment. If we add all the `building=school`s, there will be 2 OSM entities for each school in the FHRS database.

Thanks again.

**Comment by stev-0** [comment]
OK, fair enough, can't dispute that reasoning! :)
