### ISSUE TITLE
Adding address info when fhrs:id is already present in top map

### ISSUE THREAD

**Issue by spindr** [gregrs-uk/python-fhrs-osm#47]
A lot of locations in places like Bath, etc. have fhrs:id present -- but no address information.
Unfortunately, the top map in the current tool doesn't support adding fixme:addr tags to locations when the fhrs:id is present (even if there's no addr:postcode).

This would help the new quarterly addressing project (especially BS postcodes that are in Bath FHRS :-)
Thanks, Neil

**Comment by gregrs-uk** [comment]
Thanks for spotting this. Looks like a change [around line 337 to `get_overview_geojson()` in `__init__.py`](https://github.com/gregrs-uk/python-fhrs-osm/blob/master/fhrs_osm/__init__.py#L337) would solve this i.e. where the text for the map popups is defined.

I will try to have a look at this when I can but pull requests are welcome.

**Comment by gregrs-uk** [comment]
The 'Postcodes missing/mismatched' table should also get a link to add address info in JOSM.

**Comment by gregrs-uk** [comment]
Needs a bit more work before being pushed to dev server

**Comment by spindr** [comment]
Thanks for looking at this.

**Comment by gregrs-uk** [comment]
Noticed #48 whilst fixing this

**Comment by gregrs-uk** [comment]
Dev server is now updated and HTML pages have been re-created.
