### ISSUE TITLE
addtags part of JOSM links should be URL encoded

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#48]
Links for adding tags in JOSM may contain & characters. These must be URL encoded.

An example of where this is failing is FHRSID 909471 in the Bath district.

**Comment by gregrs-uk** [comment]
[Robert Whittaker writes](https://github.com/gregrs-uk/fhrs-osm-stats/issues/1):

It appears that ampersands appearing in address lines are not escaped when included in the "Add tags in JOSM" URL link. Without being escaped, they mess things up in JOSM, as the ampersand is treated as the end of the addtags query variable. See for example, the link for http://ratings.food.gov.uk/business/en-GB/920810/ in http://gregrs.dev.openstreetmap.org/fhrs/district-168.html

`http://localhost:8111/load_object?objects=w190096138&addtags=fhrs:id=920810|fixme:addr1=B & M Retail Ltd|fixme:addr2=Milton Road South|fixme:addr3=STOWMARKET|fixme:addr4=Suffolk|addr:postcode=IP14 1EJ |source:addr=FHRS Open Data`

**Comment by gregrs-uk** [comment]
addtags search: https://github.com/gregrs-uk/python-fhrs-osm/search?q=addtags&unscoped_q=addtags

Some links are created using an SQL query and directly output as part of a GeoJSON string, so would probably need to implement this using SQL rather than in Python.

**Comment by Cj-Malone** [comment]
This also happens a lot on [Brighton and Hove](https://gregrs.dev.openstreetmap.org/fhrs/district-338.html) as they frequently have `fixme:addr3=Brighton%20&%20Hove` (Brighton & Hove). I'm currently cleaning up the missing post codes that made it into OSM, but I wont be able to add the missing `source:addr=FHRS Open Data` as I don't know which nodes needed them.

**Comment by gregrs-uk** [comment]
This is implemented in [fhodot](https://github.com/gregrs-uk/fhodot/), which will soon replace the original FHRS/OSM comparison tool
