### ISSUE TITLE
Make it more obvious that users should change fixme:addr* tags added using links

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#49]
'Add tags in JOSM' links add address data to `fixme:addr*` tags in JOSM and expect users to copy the relevant data into `addr:*` tags. It should be more obvious that they are expected to do this as there are currently lots of nodes/ways with remaining `fixme:addr*` tags.

c.f. [mailing list post](https://lists.openstreetmap.org/pipermail/talk-gb/2017-October/020787.html)

**Comment by gregrs-uk** [comment]
Need to add a warning for users relating to `Add tags in JOSM` for:

* [popups in overview map when FHRS establishment matched in OSM but addr:postcode missing](https://github.com/gregrs-uk/python-fhrs-osm/blob/7539e1e63db4bca6c7c699d277465da9e15882a7/fhrs_osm/__init__.py#L361)
* [popups in suggested matches map view](https://github.com/gregrs-uk/python-fhrs-osm/blob/7539e1e63db4bca6c7c699d277465da9e15882a7/fhrs_osm/__init__.py#L444)
* [empty postcodes in postcode mismatches table](https://github.com/gregrs-uk/python-fhrs-osm/blob/7539e1e63db4bca6c7c699d277465da9e15882a7/create_output_files.py#L214)

**Comment by gregrs-uk** [comment]
Relevant [Overpass Turbo](https://overpass-turbo.eu) query:

```
[out:xml][timeout:25];
(
  node["fixme:addr1"]({{geocodeBbox:United Kingdom}});
  way["fixme:addr1"]({{geocodeBbox:United Kingdom}});
  node["fixme:addr2"]({{geocodeBbox:United Kingdom}});
  way["fixme:addr2"]({{geocodeBbox:United Kingdom}});
  node["fixme:addr3"]({{geocodeBbox:United Kingdom}});
  way["fixme:addr3"]({{geocodeBbox:United Kingdom}});
  node["fixme:addr4"]({{geocodeBbox:United Kingdom}});
  way["fixme:addr4"]({{geocodeBbox:United Kingdom}});
);
out meta;
>;
out meta qt;
```

JOSM filter string for those already fixed:
`"fixme:addr1" OR "fixme:addr2" OR "fixme:addr3" OR "fixme:addr4"`

**Comment by rjw62** [comment]
I think the ideal approach would be for any of the fixme:addr tags to trip the JOSM validator when the user tries to upload them. Whether this is by get a change in JOSM and/or changing to some other tag structure that JOSM already detects I don't know.

**Comment by gregrs-uk** [comment]
That would definitely be useful, thanks.

**Comment by gregrs-uk** [comment]
This is implemented through a warning message in [fhodot](https://github.com/gregrs-uk/fhodot/), which will soon replace the original FHRS/OSM comparison tool
