### ISSUE TITLE
Reports are not being updated

### ISSUE THREAD

**Issue by AndrewHain** [gregrs-uk/python-fhrs-osm#55]
The reports do not reflect recent changes, for instance https://www.openstreetmap.org/way/600866234 is reported as unmatched on the Richmond upon Thames map and https://www.openstreetmap.org/way/596211782 is not reported as a shop.

**Comment by gregrs-uk** [comment]
Thanks @AndrewHain. I'm afraid there is a problem with the script running on the dev server which I don't currently have time to fix. I will update this issue when I do have time, which should be over the next couple of weeks.

**Comment by gregrs-uk** [comment]
District pages should now be reflecting updates as normal. I'm just working on getting the graphs working again as R has been upgraded on the dev server.

**Comment by gregrs-uk** [comment]
Graphs should now be updating as normal.
