### ISSUE TITLE
GB Top districts graph by % of non-mismatched postcodes seems out of date

### ISSUE THREAD

**Issue by DaveVenables** [gregrs-uk/python-fhrs-osm#56]
The GB wide FHRS/OSM comparison graph of Top districts by percentage of OSM nodes with a non-mismatched postcode seems to be out of date and does not match the Districts summary.
Cambridge 81.6% and Gedling 76.4% show in top 20 graph with lower percentages. May also expect to see Erewash 79.6%. Derby 77.9% and Broxtowe 74.5%.
Other graphs seem to be updating correctly.

**Comment by gregrs-uk** [comment]
Thanks for spotting this. I've moved the issue to the [fhrs-osm-stats repository](
https://github.com/gregrs-uk/fhrs-osm-stats/issues).
