### ISSUE TITLE
Not matching where the fhrs:id tag is on a multi-polygon relation

### ISSUE THREAD

**Issue by DaveVenables** [gregrs-uk/python-fhrs-osm#57]
https://www.openstreetmap.org/relation/2523456 fhrs:id 1001957 type multipolygon
https://www.openstreetmap.org/relation/961047 fhrs:id 1074036 type multipolygon
These OSM objects are not being correctly matched to the FHRS ones and the comparison tool shows blue dots at the FHRS postcode centroids and nothing at the OSM objects.

**Comment by DaveVenables** [comment]
Upon reflection I can see that this is a duplicate of issue 6 https://github.com/gregrs-uk/python-fhrs-osm/issues/6

**Comment by gregrs-uk** [comment]
Thanks, Dave. Closing this as a duplicate.
