### ISSUE TITLE
Improve marker colours (particularly purple vs blue)

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#58]
From Robert Whittaker @rjw62 via email:

> I find it quite difficult to see the difference between the purple markers (OSM with postcode) and blue markers (unmatched FHRS entries) on the map. Could you try adding a bit more contrast between the colours there? Perhaps add a bit more red to the purple and make it a bit darker, while making the blue brighter.

**Comment by rjw62** [comment]
The top row shows current marker colours. The bottom row shows my suggested tweaks to the purple and blue ones: changing the purple from #984ea3 to #c03ca5 (slightly more red and more saturation) and the blue from #377db8 to #007fff (more blue and less red).

![image](https://user-images.githubusercontent.com/726679/50727204-9eeca000-110f-11e9-835b-b5531322364e.png)

**Comment by SK53** [comment]
Why not used ColorBrewer's standard 5 colours and then it will work for people with various forms of colour-blindness.

**Comment by gregrs-uk** [comment]
It looks like I did use a [ColorBrewer palette](http://colorbrewer2.org/#type=qualitative&scheme=Set1&n=5) originally but unfortunately none of the five-colour qualitative palettes are colourblind-safe.

**Comment by gregrs-uk** [comment]
In fact according to the simulations provided by [Color Oracle](https://colororacle.org), @rjw62's colours actually look a little easier to discern for those with the two most common forms of colour-blindness:

Deuteranopia
![deuteranopia](https://user-images.githubusercontent.com/7353938/50727541-4370e100-1114-11e9-85be-c885f21d9be2.png)

Protanopia
![protanopia](https://user-images.githubusercontent.com/7353938/50727542-4370e100-1114-11e9-9b25-10ac033c1c36.png)

**Comment by gregrs-uk** [comment]
Example for overview map:

Old
<img width="802" alt="old" src="https://user-images.githubusercontent.com/7353938/50739125-952c7080-11d3-11e9-9bdf-db00cfa6c8af.png">

New
<img width="803" alt="new" src="https://user-images.githubusercontent.com/7353938/50739126-978eca80-11d3-11e9-8f20-84452159764e.png">

**Comment by gregrs-uk** [comment]
Thanks @rjw62. [Dev server version](https://gregrs.dev.openstreetmap.org/fhrs/) should update tomorrow morning.
