### ISSUE TITLE
Support relations

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#6]
Currently only support nodes/ways

**Comment by gregrs-uk** [comment]
Currently there are 44 relations with an fhrs:id tag. These only account for 0.43% of objects with an fhrs:id tag so this issue can probably wait for now...

**Comment by rjw62** [comment]
In case it's helpful and you weren't already aware of these features of the Overpass API:
1/ You can use "nwr" in place of "node", "way" and "relation" to get all three types at once.
2/ There's a "center" geometry option that returns just a centre-point (actually the center of the objects bounding box) for ways and relations (See https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Center ). This way you don't need to collect all the nodes/members and work out a location for yourself.
With these two features, you should be able to include relations with almost no additional effort. IIRC correctly the only small change you need is for non-node objects the lat/lon coordinates are output in a slightly differently named key/place in the XML/JSON.

**Comment by gregrs-uk** [comment]
Thanks @rjw62. I use [overpy](https://github.com/DinoTools/python-overpy), which originally didn't support the `center` option, hence [this commit](https://github.com/gregrs-uk/python-fhrs-osm/commit/ca60766245c8216e3b89885cba10c9567c4b097f). However my work on overpy was subsequently merged (see [this PR](https://github.com/DinoTools/python-overpy/pull/27) and [this PR](https://github.com/DinoTools/python-overpy/pull/47)), so the `center` option could probably now be used, and should be a good way to support relations as you've suggested.

I won't be able to get to this very soon so if anyone would like to work on it, PRs are welcome.

Note to self: test generally using the latest version of `overpy` and update the version in my virtual environment on the dev server.

**Comment by rjw62** [comment]
Possible solution in pull request #72

**Comment by DaveVenables** [comment]
I've reviewed the output for Derby and a few other areas and it all looks to be correct. Numbers of missing fhrs:id values reported has reduced and a few previously missed errors have been found. As far as I can tell nothing has changed for ordinary nodes and ways and this is entirely an improvement. Thank You.

**Comment by gregrs-uk** [comment]
Thanks for checking, @DaveVenables, and thanks again @rjw62 for the pull request.
