### ISSUE TITLE
what to run to process each day?

### ISSUE THREAD

**Issue by jnicho02** [gregrs-uk/python-fhrs-osm#71]
I'm assuming that you don't start from scratch every day by running setup.sh, so do you just have a cronjob running lines copied from the last section of setup.sh? Maybe a separate .sh is required.

Not a big deal, just running it locally to test out my changes to matching.

**Comment by gregrs-uk** [comment]
I keep the configuration used for the dev server instance in a separate branch. (Not sure whether this is an ideal way to do things but it seems to work well.) [This file](https://github.com/gregrs-uk/python-fhrs-osm/blob/dev-server/update.sh) runs each day, along with a few others relating to the statistics. Hope that helps.

**Comment by jnicho02** [comment]
Ah right, gotcha! For my testing purposes I'm running for just Brighton & Hove so the end of setup.sh works fine. Thank you
